name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v1

        with:
          flutter-version: '1.11.0'
          channel: 'beta'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
